name: divestore
description: "Types and storage for dive data"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.10.4

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  json_serializable: ^6.11.3
  build_runner: ^2.10.4
