name: divestore
description: "Types and storage for dive data"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.10.4

dependencies:
  json_annotation: ^4.9.0
  sqflite: ^2.4.2
  uuid: ^4.5.2
  xml: ^6.6.1

dev_dependencies:
  json_serializable: ^6.11.3
  build_runner: ^2.10.4
