name: divestore
description: "Types and storage for dive data"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.10.4

dependencies:
  collection: ^1.18.0
  glob: ^2.1.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  protobuf: ^6.0.0
  uuid: ^4.5.2
  xml: ^6.6.1

dev_dependencies:
  json_serializable: ^6.11.3
  build_runner: ^2.10.4
  test: ^1.25.0
