name: libdivecomputer
description: "A new Dart FFI package project."
version: 0.0.1

environment:
  sdk: ^3.10.4

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.4
  glob: ^2.1.3
  hooks: ^1.0.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  native_toolchain_c: ^0.17.1

dev_dependencies:
  build_runner: ^2.10.4
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.3
  test: ^1.25.8
