name: libdivecomputer
description: "Wrapper for libdivecomputer into Flutter"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.10.4

dependencies:
  btstore: {path: ../btstore}
  code_assets: ^1.0.0
  ffi: ^2.1.4
  glob: ^2.1.3
  hooks: ^1.0.0
  logging: ^1.3.0
  native_toolchain_c: ^0.17.1

dev_dependencies:
  build_runner: ^2.10.4
  ffigen: ^20.1.1
  test: ^1.25.8
