name: btstore
description: "Storage for dive data"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.10.4

dependencies:
  btmodels: {path: ../btmodels}
  collection: ^1.18.0
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  glob: ^2.1.3
  intl: ^0.20.2
  logging: ^1.3.0
  meta: ^1.17.0
  protobuf: ^6.0.0
  uuid: ^4.5.2
  xml: ^6.6.1

dev_dependencies:
  build_runner: ^2.10.4
  dependency_validator: ^3.2.3
  test: ^1.25.0
